// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI0CR5wPWFNgg358SOB8AlaHbOc8USVRw',
    appId: '1:317687385872:web:3ac6a75112c93eb8589f95',
    messagingSenderId: '317687385872',
    projectId: 'nileassist-f1752',
    authDomain: 'nileassist-f1752.firebaseapp.com',
    storageBucket: 'nileassist-f1752.firebasestorage.app',
    measurementId: 'G-6T9FW459M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS1H_jbj_otUhRR4t4NQCPuozy4zsOGEQ',
    appId: '1:317687385872:android:c6eaf5143b8b5b99589f95',
    messagingSenderId: '317687385872',
    projectId: 'nileassist-f1752',
    storageBucket: 'nileassist-f1752.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHdB9G7teBn_qaMxhU8DZCSOcRlQ2R3cA',
    appId: '1:317687385872:ios:bb41a715da467f31589f95',
    messagingSenderId: '317687385872',
    projectId: 'nileassist-f1752',
    storageBucket: 'nileassist-f1752.firebasestorage.app',
    iosBundleId: 'com.example.nileassist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHdB9G7teBn_qaMxhU8DZCSOcRlQ2R3cA',
    appId: '1:317687385872:ios:bb41a715da467f31589f95',
    messagingSenderId: '317687385872',
    projectId: 'nileassist-f1752',
    storageBucket: 'nileassist-f1752.firebasestorage.app',
    iosBundleId: 'com.example.nileassist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI0CR5wPWFNgg358SOB8AlaHbOc8USVRw',
    appId: '1:317687385872:web:e23c0168e16bf5b6589f95',
    messagingSenderId: '317687385872',
    projectId: 'nileassist-f1752',
    authDomain: 'nileassist-f1752.firebaseapp.com',
    storageBucket: 'nileassist-f1752.firebasestorage.app',
    measurementId: 'G-67XTGXWXQ0',
  );
}
